"""Abstract interfaces for step 4: table comparison and reporting."""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

from react_review.steps.data_extraction.schemas import ExtractedTable
from react_review.steps.table_comparison.schemas import (
    EvaluationReport,
    TableComparisonResult,
)

if TYPE_CHECKING:
    from react_review.pipeline.schemas import EvidenceFieldSchema


class TableComparator(ABC):
    """Interface for comparing a student's table against model-generated tables."""

    @abstractmethod
    async def compare(
        self,
        student_table: ExtractedTable,
        model_tables: list[ExtractedTable],
        schema: "list[EvidenceFieldSchema] | None" = None,
    ) -> TableComparisonResult:
        """Compare a student table with one or more model-generated tables.

        Args:
            student_table: The student's submitted extraction.
            model_tables: Tables generated by different extractors.
            schema: Optional rich evidence schema (one entry per column
                of the student's table). When provided, the comparator
                uses each entry's ``type`` to dispatch the comparison
                method, applies per-field thresholds from
                ``threshold_match`` / ``threshold_partial``, and skips
                fields flagged ``is_metadata=True`` (Step 2 already
                validates author / year / doi). When ``None`` or empty,
                the comparator falls back to value-type detection plus
                default thresholds, preserving backward compatibility
                with legacy callers.

        Returns:
            Comparison result with per-field diffs and agreement rate.
        """


class ReportGenerator(ABC):
    """Interface for generating a final evaluation report."""

    @abstractmethod
    async def generate(
        self,
        comparison_results: list[TableComparisonResult],
        run_id: str,
    ) -> EvaluationReport:
        """Generate a final evaluation report from comparison results."""
